# ベースイメージの指定
FROM golang:alpine

RUN apk add --no-cache gcc musl-dev

# 作業ディレクトリの設定
WORKDIR /app

# imagesディレクトリの作成
RUN mkdir -p ./images

# Goモジュールファイルをコピー
COPY go.mod .
COPY go.sum .

# 依存関係をダウンロード
RUN go mod download

# データベースファイルのコピー
COPY db/mercari.sqlite3 /app/db/

# Goのソースファイルをコピー
COPY ./app/main.go .

# ビルド
RUN CGO_ENABLED=1 go build -o main main.go

# ポートの公開
EXPOSE 9000

# 実行コマンドの指定
CMD ["./main"]
# RUN addgroup -S mercari && adduser -S trainee -G mercari
# RUN chown -R trainee:mercari /path/to/db

# USER trainee

#CMD ["go", "version"]
